// src/constants/api.js
export const API = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    ME: '/auth/me',
  },
  MENU_SETTINGS: {
    BASE: '/menu-settings',
    BY_ROLE: (role) => `/menu-settings/roles/${role}`,
    BULK: '/menu-settings/bulk',
  },
  USERS: { BASE: '/users', BY_ID: (id) => `/users/${id}` },
  PATIENTS: { BASE: '/patients', BY_ID: (id) => `/patients/${id}`, SEARCH: '/patients/search' },
  APPOINTMENTS: { BASE: '/appointments', BY_ID: (id) => `/appointments/${id}` },
  DOCTORS: { BASE: '/doctors', BY_ID: (id) => `/doctors/${id}` },
  HOSPITALS: { BASE: '/hospitals', BY_ID: (id) => `/hospitals/${id}` },
  BILLING: { BASE: '/billing', BY_ID: (id) => `/billing/${id}`, PAYMENTS: '/billing/payments' },
  INVENTORY: { BASE: '/inventory', BY_ID: (id) => `/inventory/${id}` },
  LAB: { ORDERS: '/lab/orders', RESULTS: '/lab/results', CATALOG: '/lab/catalog', SAMPLES: '/lab/samples' },
  RADIOLOGY: { ORDERS: '/radiology/orders', RESULTS: '/radiology/results', EQUIPMENT: '/radiology/equipment', CATALOG: '/radiology/catalog' },
  AMBULANCE: { BASE: '/ambulance', DISPATCH: '/ambulance/dispatch', FLEET: '/ambulance/fleet', CALLS: '/ambulance/calls', DRIVERS: '/ambulance/drivers' },
  PHARMACY: {
    PRESCRIPTIONS: '/pharmacy/prescriptions',
    MEDICINES: '/medicine',
    MEDICINE_BATCH: '/medicine-batch',
    STOCK: '/pharmacy/stock',
    ORDERS: '/pharmacy/purchase-orders',
    SUPPLIERS: '/supplier',
    MEDICINE_CATEGORY: '/medicine-category',
    MEDICINE_SUBCATEGORY: '/medicine-subcategory',
    MEDICINE_COMPANY: '/medicine-company',
    MEDICINE_UNIT: '/medicine-unit',
    SHELF_MASTER: '/shelf-master',
    PURCHASE_MASTER: '/purchase-master',
    PURCHASE_DETAILS: '/purchase-master',
    SALES_MASTER: '/sales-master',
    SALES_DETAILS: '/sales-master',
    STOCK_LEDGER: '/stock-ledger',
    PURCHASE_RETURN: '/purchase-return',
    SALES_RETURN: '/sales-return',
    EXPIRY: '/expiry',
    SELL_MEDICINE: '/sell-medicine',
    PAYMENT: '/pharmacy/payment',
    INVOICE: '/pharmacy/invoice',
  },
  IN_STOCKS: '/in-stocks',
  STOCK_MASTERS: '/stock-masters',
  REPORTS: '/reports',
};
