

export const ROUTES = {
  // Auth
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',

  // Super Admin
  SUPER_ADMIN: {
    DASHBOARD: '/super-admin/dashboard',
    HOSPITALS: '/super-admin/hospitals',
    STOCK_ITEM: '/super-admin/stocks/item',
    STOCK_MASTER: '/super-admin/stocks/master',
    INSTOCK: '/super-admin/stocks/instock',
    OUTSTOCK: '/super-admin/stocks/outstock',
    STOCKS: '/super-admin/stocks',
    STOCK_ITEMS: '/super-admin/stocks/items',
    ADDSTOCK: '/super-admin/stocks/add',
    INSTOCK: '/super-admin/stocks/instock',
    USED: '/super-admin/stocks/used',
    RETURN: '/super-admin/stocks/return',
    HOSPITAL: '/super-admin/hospitals/hospital',
    DEPARTMENTS: '/super-admin/hospitals/department',
    HOSPITAL_DOCTORS: '/super-admin/hospitals/hospital-doctors',
    SUB_ADMINS: '/super-admin/sub-admins',
    ROLES: '/super-admin/roles',
    PERMISSIONS: '/super-admin/permissions',
    SIDEBAR_SETUP: '/super-admin/sidebar-setup',
    SETTINGS: '/super-admin/system-settings',
    AUDIT_LOGS: '/super-admin/audit-logs',
    REPORTS: '/super-admin/reports',
    // Hospital Modules
    IPD: '/super-admin/ipd',
    IPD_PATIENTS: '/super-admin/ipd/ipd-patients',
    WARD: '/super-admin/ipd/ward',
    ROOM: '/super-admin/ipd/room',
    BED: '/super-admin/ipd/bed',
    BED_STATUS: '/super-admin/ipd/bed-status',
    ADD_IPD: '/super-admin/ipd/add-ipd',
    VIEW_IPD: "/super-admin/ipd/view-ipd",
    ADMITTED_PATIENTS: '/super-admin/ipd/admitted-patients',
    DISCHARGED_PATIENTS: '/super-admin/ipd/discharged-patients',
    DAILY_OBSERVATIONS: "/super-admin/ipd/daily-observations",
    OPD: '/super-admin/opd',
    OPD_ADD: '/super-admin/opd/add',
    DEPARTMENT: '/super-admin/opd/department',
    OPD_DOCTORS: '/super-admin/opd/opd-doctors',
    OPD_CATEGORY: '/super-admin/opd/category',
    OPD_CHARGE_CATEGORY: '/super-admin/opd/charge-category',
    OPD_DOCTOR_FEES: '/super-admin/opd/doctor-fees',
    ADD_PRESCRIPTION: '/super-admin/opd/add-prescription',
    PATIENT_SCANNER: '/super-admin/opd/patient-scanner',
    ADMIT: '/super-admin/opd/admit',
    PHARMA: '/super-admin/pharma',
    PHARMACY_PRESCRIPTION: '/super-admin/pharma/pharmacy-prescription',
    PHARMACY_SELL: '/super-admin/pharma/sell',
    PHARMACY_SALES: '/super-admin/pharma/sales',
    PHARMACY_PURCHASES: '/super-admin/pharma/purchases',
    PHARMACY_PURCHASE_RETURNS: '/super-admin/pharma/purchase-returns',
    PHARMACY_SALES_RETURNS: '/super-admin/pharma/sales-returns',
    PHARMACY_EXPIRY: '/super-admin/pharma/expiry',
    PHARMACY_STOCK_LEDGER: '/super-admin/pharma/stock-ledger',
    PHARMACY_REPORTS: '/super-admin/pharma/reports',
    ITEM_MASTER: '/super-admin/pharma/item-master',
    ITEM_CATEGORY: '/super-admin/pharma/item-category',
    ITEM_SUBCATEGORY: '/super-admin/pharma/itemsubcategory',
    SELF_MASTER: '/super-admin/pharma/self-master',
    SUPPLIER: '/super-admin/pharma/supplier',
    ADD_MEDICINES: '/super-admin/pharma/medicines',
    IMPORT_MEDICINES_PAGE: '/super-admin/pharma/medicines/importmedicines',
    PURCHASE_PAGE: '/super-admin/pharma/medicines/purchasepage',
    PURCHASE_NEW_PAGE: '/super-admin/pharma/medicines/purchasepage/new',
    PURCHASE_EDIT_PAGE: '/super-admin/pharma/medicines/purchasepage/edit/:id',
    PHARMA_GENERATE_BILL_PAGE: '/super-admin/pharma/generate-bill',
    AMBULANCE_MGT: '/super-admin/ambulance',
    APPOINTMENTS: '/super-admin/appointments',
    BOOK_APPOINTMENT: '/super-admin/appointments/book-appointment',
    DOCTOR_WISE: '/super-admin/appointments/doctor-wise',
    QUEUE: '/super-admin/appointments/queue',
    DOCTORS: '/super-admin/doctors',
    ADD_DOCTORS: '/super-admin/doctors/add-doctors',
    VIEW_DOCTOR: '/super-admin/doctors/:id',
    EDIT_DOCTOR: '/super-admin/doctors/:id/edit',
    PATIENTS: '/super-admin/patients',
    PATIENT_CREATE: '/super-admin/patients/create',
    PATIENT_VIEW: '/super-admin/patients/:id',
    PATIENT_EDIT: '/super-admin/patients/:id/edit',
    IVF: '/super-admin/ivf',
    IVF_DETAILS: '/super-admin/ivf/:id',
    PATHOLOGY: '/super-admin/pathology',
    PATHOLOGY_PRESCRIPTION: '/super-admin/pathology/pathology-prescription',
    PATHOLOGY_ORDERS: '/super-admin/pathology/orders',
    PATHOLOGY_CATEGORY: '/super-admin/pathology/category',
    PATHOLOGY_SUBCATEGORY: '/super-admin/pathology/subcategory',
    ADD_PATHOLOGY_TEST: '/super-admin/pathology/pathology-test',
    PATHOLOGY_GENERATE_BILL_PAGE: '/super-admin/pathology/generate-bill',
    RADIOLOGY: '/super-admin/radiology',
    RADIOLOGY_PRESCRIPTION: '/super-admin/radiology/radiology-prescription',
    ORDERS: '/super-admin/radiology/orders',
    CATEGORY: '/super-admin/radiology/category',
    CHARGE_CATEGORY: '/super-admin/radiology/charge-category',
    CHARGE_NAME: '/super-admin/radiology/charge-name',
    TEST_PARAMETERS: '/super-admin/radiology/test-parameters',
    REPORT: '/super-admin/radiology/report',
    RADIOLOGY_INVOICE: '/super-admin/radiology/radiology-invoice',
    ADD_RADIOLOGY_TEST: '/super-admin/radiology/add-test',
    RADIOLOGY_GENERATE_BILL_PAGE: '/super-admin/radiology/generate-bill',
    //Billing
    APPOINTMENT_BILL_PAGE: '/super-admin/appointmentbill',
    PHARMACY_BILL_PAGE: '/super-admin/pharmacybill',
    PATHOLOGY_BILL_PAGE: '/super-admin/pathologybill',
    RADIOLOGY_BILL_PAGE: '/super-admin/radiologybill',

    APPOINTMENT_BILL: '/super-admin/appointmentbill',
    PHARMACY_BILL: '/super-admin/pharmacybill',
    PATHOLOGY_BILL: '/super-admin/pathologybill',
    RADIOLOGY_BILL: '/super-admin/radiologybill',
    PATHOLOGY_CHARGE_CATEGORY: '/super-admin/pathology/charge-category',
    PATHOLOGY_CHARGE_NAME:     '/super-admin/pathology/charge-name',

    // Blood Bank
    BLOOD_BANK_STATUS: '/super-admin/blood-bank/status',
    BLOOD_BANK_DONOR: '/super-admin/blood-bank/donor',
    BLOOD_BANK_BLOOD_ISSUE: '/super-admin/blood-bank/blood-issue',
    BLOOD_BANK_COMPONENT_ISSUE: '/super-admin/blood-bank/component-issue',

    USER_MANAGEMENT: '/super-admin/user/user-management',
    EMERGENCY: '/super-admin/emergency',
    ADD_EMERGENCY: '/super-admin/emergency/add',
    OT: '/super-admin/ot',
    PRE_OT: '/super-admin/ot/pre-ot',
    OT_INVENTORY: '/super-admin/ot/inventory',
    OT_PHARMA: '/super-admin/ot/ot-pharma',
    OT_BILL: '/super-admin/ot/bill',
  },

  // Sub Admin
  SUB_ADMIN: {
    DASHBOARD: '/sub-admin/dashboard',
    HOSPITALS: '/sub-admin/hospital-management',
    USERS: '/sub-admin/user-management',
    REPORTS: '/sub-admin/reports',
    // Hospital Modules
    IPD: '/sub-admin/ipd',
    OPD: '/sub-admin/opd',
    PHARMA: '/sub-admin/pharmacy',
    AMBULANCE_MGT: '/sub-admin/ambulance',
    APPOINTMENTS: '/sub-admin/appointments',
    DOCTORS: '/sub-admin/doctors',
    PATIENTS: '/sub-admin/patients',
    IVF: '/sub-admin/ivf',
    IVF_DETAILS: '/sub-admin/ivf/:id',
    PAYMENTS: '/sub-admin/payments',
    PATHOLOGY: '/sub-admin/pathology',
    RADIOLOGY: '/sub-admin/radiology',

    // Blood Bank
    BLOOD_BANK_STATUS: '/sub-admin/blood-bank/status',
    BLOOD_BANK_DONOR: '/sub-admin/blood-bank/donor',
    BLOOD_BANK_BLOOD_ISSUE: '/sub-admin/blood-bank/blood-issue',
    BLOOD_BANK_COMPONENT_ISSUE: '/sub-admin/blood-bank/component-issue',
  },

  // Hospital Admin
  HOSPITAL_ADMIN: {
    DASHBOARD: '/hospital-admin/dashboard',
    DOCTORS: '/hospital-admin/doctors',
    STAFF: '/hospital-admin/staff',
    DEPARTMENTS: '/hospital-admin/departments',
    WARDS: '/hospital-admin/wards-beds',
    INVENTORY: '/hospital-admin/inventory',
    REPORTS: '/hospital-admin/reports',
    SETTINGS: '/hospital-admin/settings',
  },

  // Front Desk
  FRONT_DESK: {
    DASHBOARD: '/front-desk/dashboard',
    PATIENTS: '/front-desk/patients',
    REGISTRATION: '/front-desk/patient-registration',
    APPOINTMENTS: '/front-desk/appointments',
    TOKEN_QUEUE: '/front-desk/token-queue',
    OPD: '/front-desk/opd',
    IPD: '/front-desk/ipd',
    PHARMACY: '/front-desk/pharmacy',
    RADIOLOGY: '/front-desk/radiology',
    PATHOLOGY: '/front-desk/pathology',
    AMBULANCE: '/front-desk/ambulance',
    BILLING: '/front-desk/billing',
  },

  // Accountant
  ACCOUNTANT: {
    DASHBOARD: '/accountant/dashboard',
    PATIENTS: '/accountant/Patients',
    BILLING: '/accountant/billing',
    APPOINTMENTS: '/accountant/appointments',
    IPD: '/accountant/ipd',
    OPD: '/accountant/opd',
    PHARMACY: '/accountant/pharmacy',
    PATHOLOGY: '/accountant/pathology',
    RADIOLOGY: '/accountant/radiology',
    AMBULANCE: '/accountant/ambulance',
    PAYMENTS: '/accountant/payments',
    EXPENSES: '/accountant/expenses',
    INSURANCE: '/accountant/insurance',
    REPORTS: '/accountant/reports',
  },

  // Nurse
  NURSE: {
    DASHBOARD: '/nurse/dashboard',
    PATIENTS: '/nurse/patients',
    IPD: '/nurse/ipd',
    OPD: '/nurse/opd',
    VITALS: '/nurse/patient-vitals',
    MEDICATION: '/nurse/medication',
    WARD: '/nurse/ward-management',
    CARE_PLANS: '/nurse/care-plans',
    HANDOVER: '/nurse/shift-handover',
  },

  // Laboratory
  LABORATORY: {
    DASHBOARD: '/laboratory/dashboard',
    TEST_ORDERS: '/laboratory/test-orders',
    TEST_RESULTS: '/laboratory/test-results',
    SAMPLES: '/laboratory/sample-collection',
    CATALOG: '/laboratory/test-catalog',
    REPORTS: '/laboratory/reports',
  },

  // Radiology
  RADIOLOGY: {
    DASHBOARD: '/radiology/dashboard',
    PATIENTS: '/radiology/patients',
    BILLING: '/radiology/billing',
    OPD: '/radiology/opd',
    IPD: '/radiology/ipd',
    REPORTS: '/radiology/reports',
    SCAN_ORDERS: '/radiology/scan-orders',
    SCAN_RESULTS: '/radiology/scan-results',
    IMAGING: '/radiology/imaging',
    EQUIPMENT: '/radiology/equipment',
    CATALOG: '/radiology/test-catalog',
  },

  // Ambulance
  AMBULANCE: {
    DASHBOARD: '/ambulance/dashboard',
    DISPATCH: '/ambulance/dispatch',
    FLEET: '/ambulance/fleet',
    CALLS: '/ambulance/calls',
    DRIVERS: '/ambulance/drivers',
  },

  // Pharmacist
  PHARMACIST: {
    DASHBOARD: '/pharmacist/dashboard',
    PRESCRIPTIONS: '/pharmacist/prescriptions',
    OPD: '/pharmacist/opd',
    IPD: '/pharmacist/ipd',
    BILLING: '/pharmacist/billing',
    SELL: '/pharmacist/sell',
    PURCHASE: '/pharmacist/purchase',
    MEDICINES: '/pharmacist/medicines',
    MEDICINE_CATEGORY: '/pharmacist/medicine-category',
    MEDICINE_SUBCATEGORY: '/pharmacist/medicine-subcategory',
    SELF_MASTER: '/pharmacist/self-master',
    STOCK: '/pharmacist/stock',
    PURCHASE_ORDERS: '/pharmacist/purchase-orders',
    SUPPLIERS: '/pharmacist/suppliers',
    REPORTS: '/pharmacist/reports',
    SALES: '/pharmacist/sales',
    PURCHASES: '/pharmacist/purchases',
    PURCHASE_RETURNS: '/pharmacist/purchase-returns',
    SALES_RETURNS: '/pharmacist/sales-returns',
    EXPIRY: '/pharmacist/expiry',
    STOCK_LEDGER: '/pharmacist/stock-ledger',
  },
  // Doctor
  DOCTOR: {
    DASHBOARD: '/doctor/dashboard',
    PATIENTS: '/doctor/patients',
    OPD: '/doctor/opd',
    OPD_ADD: '/doctor/opd/add',
    OPD_PRESCRIPTION: '/doctor/opd/prescription',
    EMERGENCY: '/doctor/emergency',
    EMERGENCY_ADD: '/doctor/emergency/add',
    EMERGENCY_EDIT: '/doctor/emergency/edit/:id',
    EMERGENCY_VIEW: '/doctor/emergency/view/:id',
    IPD: '/doctor/ipd',
    IPD_ADD: '/doctor/ipd/add',
    IPD_VIEW: '/doctor/ipd/:id',
    IVF: '/doctor/ivf',
    OT: '/doctor/ot',
    OT_PRE: '/doctor/ot/pre-ot',
    OT_BILL: '/doctor/ot/bill',
  },

  // Receptionist
  RECEPTIONIST: {
    DASHBOARD: '/receptionist/dashboard',
    PATIENTS: '/receptionist/patients',
    OPD: '/receptionist/opd',
    EMERGENCY: '/receptionist/emergency',
    IPD: '/receptionist/ipd',
    DOCTORS: '/receptionist/doctors',
    PROFILE:   '/receptionist/profile',
    SETTINGS:  '/receptionist/settings',
  },

  // Lab Technician
  LAB_TECHNICIAN: {
    DASHBOARD: '/lab-technician/dashboard',
    PATHOLOGY: '/lab-technician/pathology',
    PATHOLOGY_ORDERS: '/lab-technician/pathology/orders',
    PATHOLOGY_TEST: '/lab-technician/pathology/add-test',
    PATHOLOGY_CATEGORY: '/lab-technician/pathology/category',
    PATHOLOGY_SUBCATEGORY: '/lab-technician/pathology/subcategory',
    PATHOLOGY_CHARGE_CATEGORY: '/lab-technician/pathology/charge-category',
    PATHOLOGY_CHARGE_NAME: '/lab-technician/pathology/charge-name',
    PATHOLOGY_BILL: '/lab-technician/pathology/billing',
    STOCKS: '/lab-technician/stocks',
  },

  // Radiologist
  RADIOLOGIST: {
    DASHBOARD: '/radiologist/dashboard',
    RADIOLOGY: '/radiologist/radiology',
    RADIOLOGY_ORDERS: '/radiologist/radiology/orders',
    RADIOLOGY_TEST: '/radiologist/radiology/add-test',
    RADIOLOGY_CATEGORY: '/radiologist/radiology/category',
    RADIOLOGY_CHARGE_CATEGORY: '/radiologist/radiology/charge-category',
    RADIOLOGY_CHARGE_NAME: '/radiologist/radiology/charge-name',
    RADIOLOGY_TEST_PARAMETERS: '/radiologist/radiology/test-parameters',
    RADIOLOGY_INVOICE: '/radiologist/radiology/invoice',
    RADIOLOGY_BILL: '/radiologist/radiology/billing',
  },// Billing Staff
  BILLING_STAFF: {
    DASHBOARD: '/billing/dashboard',
    APPOINTMENT_BILL: '/billing/appointment-bill',
    RADIOLOGY_BILL: '/billing/radiology-bill',
    PATHOLOGY_BILL: '/billing/pathology-bill',
    PHARMACY_BILL: '/billing/pharmacy-bill',
    STOCKS: '/billing/stocks',
  },

  // IPD Staff
  IPD_STAFF: {
    DASHBOARD: '/ipd-staff/dashboard',
    IPD: '/ipd-staff/ipd',
    IPD_ADD: '/ipd-staff/ipd/add',
    IPD_VIEW: '/ipd-staff/ipd/:id',
    ADMITTED_PATIENTS: '/ipd-staff/ipd/admitted',
    DISCHARGED_PATIENTS: '/ipd-staff/ipd/discharged',
    WARD: '/ipd-staff/ward',
    ROOM: '/ipd-staff/room',
    BED: '/ipd-staff/bed',
    BED_STATUS: '/ipd-staff/bed-status',
  },

  // Shared
  PROFILE: '/profile',
  SETTINGS: '/settings',
  NOTIFICATIONS: '/notifications',
  UNAUTHORIZED: '/unauthorized',
  NOT_FOUND: '*',
  SERVER_ERROR: '/500',
};
