import {
  Activity,
  Ambulance,
  ArrowLeftRight,
  BarChart2,
  BarChart3,
  Bed,
  BedDouble,
  BookOpen,
  Boxes,
  Building,
  Building2,
  Baby,
  Calendar,
  CalendarCheck,
  CalendarIcon,
  Clipboard,
  ClipboardCheckIcon,
  ClipboardList,
  ClipboardPen,
  CreditCard,
  FileCheck,
  FileText,
  FileText as FileTextIcon,
  FlaskConical,
  HeartHandshake,
  HeartPulse,
  Hospital,
  HospitalIcon,
  ImageIcon,
  IndianRupee,
  KeyRound,
  LayoutDashboard,
  ListOrdered,
  MenuIcon,
  Monitor,
  Package,
  PackageOpen,
  Phone,
  Pill,
  PillIcon,
  Radio,
  Receipt,
  ReceiptIcon,
  ReceiptText,
  Scan,
  ScanLine,
  Scissors,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Stethoscope,
  Tags,
  TestTube,
  Ticket,
  TrendingDown,
  Truck,
  User2,
  UserCheck,
  UserCircle,
  UserPlus,
  UserRound,
  Users,
  Wrench,
  Droplets,
  PackageCheck,
  PackageMinus,
  Camera,
  AlertTriangle as AlertTriangleIcon,
  PackageIcon,
  Plus
} from "lucide-react";
import { ROUTES } from "@constants/routes";
import { ROLES } from "@constants/roles";

const ALL_ROLES = Object.values(ROLES);

// subItems is optional — leaf items omit it entirely
const createItem = ({
  label,
  path,
  icon,
  group,
  role,
  permissionKey,
  allowedRoles = ALL_ROLES,
  subItems,
}) => ({
  label,
  path,
  icon,
  group,
  allowedRoles,
  permissionKey,
  ...(subItems ? { subItems } : {}),
});

export const SIDEBAR_NAV_ITEMS = {

  // ─────────────────────────────────────────────────────────────
  // SUPER ADMIN
  // ─────────────────────────────────────────────────────────────
  [ROLES.SUPER_ADMIN]: [
    /* ── MAIN ── */
    createItem({
      label: "Dashboard",
      path: ROUTES.SUPER_ADMIN.DASHBOARD,
      icon: <LayoutDashboard size={17} />,
      group: "Main",
    }),

    /* ── PATIENT FLOW ── */
    createItem({
      label: "Patients",
      path: ROUTES.SUPER_ADMIN.PATIENTS,
      icon: <ClipboardList size={17} />,
      group: "Patient Flow",
      permissionKey: { resource: "patient", action: "read" },
    }),

    createItem({
  label: "OPD",
  path: ROUTES.SUPER_ADMIN.OPD,
  icon: <Stethoscope size={17} />,
  group: "Patient Flow",
  permissionKey: [
    { resource: "opd", action: "view"   },
    { resource: "opd", action: "read"   },
    { resource: "opd", action: "create" },
  ],
  subItems: [
    { label: "Overview",        path: "/super-admin/opd",                 icon: <LayoutDashboard size={13} />, exact: true },
    { label: "Patient Scanner", path: "/super-admin/opd/patient-scanner", icon: <ScanLine size={13} />,       permissionKey: { resource: "patient", action: "read" } },
    { label: "E-Prescription",  path: "/super-admin/opd/add-prescription", icon: <ClipboardPen size={13} />, permissionKey: { resource: "prescription", action: "create" } },
    { label: "Department",      path: "/super-admin/opd/department",      icon: <Building size={13} />,       permissionKey: { resource: "opd", action: "view" } },
    { label: "Doctor Master",   path: "/super-admin/opd/opd-doctors",     icon: <UserRound size={13} />,      permissionKey: { resource: "doctor", action: "read" } },
    { label: "OPD Category",    path: "/super-admin/opd/category",        icon: <Tags size={13} />,           permissionKey: { resource: "opd", action: "view" } },
    { label: "Doctor Fees",     path: "/super-admin/opd/doctor-fees",     icon: <ReceiptText size={13} />,    permissionKey: { resource: "opd", action: "view" } },
  ],
}),

    createItem({
      label: "Emergency",
      path: ROUTES.SUPER_ADMIN.EMERGENCY,
      icon: <AlertTriangleIcon size={17} />,
      group: "Patient Flow",
      permissionKey: { resource: "emergency", action: "view" },
    }),

    createItem({
  label: "IPD",
  path: ROUTES.SUPER_ADMIN.IPD,
  icon: <BedDouble size={17} />,
  group: "Patient Flow",
  permissionKey: [
    { resource: "ipd_admission", action: "read" },
    { resource: "ipd_discharge", action: "read" },
    { resource: "ward",          action: "read" },
    { resource: "room",          action: "read" },
    { resource: "bed",           action: "read" },
    { resource: "ipd",           action: "view" },
  ],
  subItems: [
    { label: "Overview",            path: "/super-admin/ipd",                     icon: <LayoutDashboard size={13} />, exact: true },
    { label: "Ward",                path: "/super-admin/ipd/ward",                icon: <Hospital size={13} />,       permissionKey: { resource: "ward",          action: "read" } },
    { label: "Room",                path: "/super-admin/ipd/room",                icon: <Building size={13} />,       permissionKey: { resource: "room",          action: "read" } },
    { label: "Bed",                 path: "/super-admin/ipd/bed",                 icon: <Bed size={13} />,            permissionKey: { resource: "bed",           action: "read" } },
    { label: "Admitted Patients",   path: "/super-admin/ipd/admitted-patients",   icon: <UserRound size={13} />,      permissionKey: { resource: "ipd_admission", action: "read" } },
    { label: "Discharged Patients", path: "/super-admin/ipd/discharged-patients", icon: <UserCheck size={13} />,      permissionKey: { resource: "ipd_discharge", action: "read" } },
    { label: "Daily Observations",  path: "/super-admin/ipd/daily-observations",  icon: <ClipboardPen size={13} />,   permissionKey: { resource: "ipd",           action: "view" } },
  ],
}),
    /* ── CLINICAL ── */
    createItem({
      label: "Doctors",
      path: ROUTES.SUPER_ADMIN.DOCTORS,
      icon: <UserRound size={17} />,
      group: "Clinical",
      permissionKey: { resource: "doctor", action: "read" },
    }),
    createItem({
      label: "Pathology",
      path: ROUTES.SUPER_ADMIN.PATHOLOGY,
      icon: <FlaskConical size={17} />,
      group: "Clinical",

      permissionKey: [
    { resource: "pathology_overview",    action: "read" },
    { resource: "pathology_master",      action: "read" },
    { resource: "pathology_order",       action: "read" },
    { resource: "pathology_category",    action: "read" },
    { resource: "pathology_subcategory", action: "read" },
  ],
  subItems: [
    { label: "Overview",    path: "/super-admin/pathology",                 icon: <LayoutDashboard size={13} />, exact: true, permissionKey: { resource: "pathology_overview",    action: "read" } },
    { label: "Test",        path: "/super-admin/pathology/pathology-test",  icon: <TestTube size={13} />,                    permissionKey: { resource: "pathology_master",      action: "read" } },
    { label: "Orders",      path: "/super-admin/pathology/orders",          icon: <ListOrdered size={13} />,                 permissionKey: { resource: "pathology_order",       action: "read" } },
    { label: "Category",    path: "/super-admin/pathology/category",        icon: <Tags size={13} />,                        permissionKey: { resource: "pathology_category",    action: "read" } },
    { label: "SubCategory", path: "/super-admin/pathology/subcategory",     icon: <Tags size={13} />,                        permissionKey: { resource: "pathology_subcategory", action: "read" } },
  ],
    }),
    createItem({
      label: "Radiology",
      path: ROUTES.SUPER_ADMIN.RADIOLOGY,
      icon: <Scan size={17} />,
      group: "Clinical",

      permissionKey: [
    { resource: "radiology_overview",         action: "read" },
    { resource: "radiology_master",           action: "read" },
    { resource: "radiology_order",            action: "read" },
    { resource: "radiology_category",         action: "read" },
    { resource: "radiology_charge_category",  action: "read" },
    { resource: "radiology_charge_name",      action: "read" },
    { resource: "radiology_test_parameter",   action: "read" },
  ],
  subItems: [
    { label: "Overview",        path: "/super-admin/radiology",                   icon: <LayoutDashboard size={13} />, exact: true, permissionKey: { resource: "radiology_overview",        action: "read" } },
    { label: "Tests",           path: "/super-admin/radiology/add-test",          icon: <Scan size={13} />,                        permissionKey: { resource: "radiology_master",          action: "read" } },
    { label: "Orders",          path: "/super-admin/radiology/orders",            icon: <ListOrdered size={13} />,                 permissionKey: { resource: "radiology_order",           action: "read" } },
    { label: "Category",        path: "/super-admin/radiology/category",          icon: <Tags size={13} />,                        permissionKey: { resource: "radiology_category",        action: "read" } },
    { label: "Charge Category", path: "/super-admin/radiology/charge-category",   icon: <Tags size={13} />,                        permissionKey: { resource: "radiology_charge_category", action: "read" } },
    { label: "Charge Name",     path: "/super-admin/radiology/charge-name",       icon: <IndianRupee size={13} />,                 permissionKey: { resource: "radiology_charge_name",     action: "read" } },
    { label: "Test Parameters", path: "/super-admin/radiology/test-parameters",   icon: <SlidersHorizontal size={13} />,           permissionKey: { resource: "radiology_test_parameter",  action: "read" } },
  ],
  
    }),
    createItem({
      label: "Blood Bank",
      path: ROUTES.SUPER_ADMIN.BLOOD_BANK_STATUS,
      icon: <Droplets size={17} />,
      group: "Clinical",
      permissionKey: { resource: "bloodBank", action: "view" },
      subItems: [
        { label: "Overview",            path: "/super-admin/blood-bank/status",          icon: <LayoutDashboard size={13} />, exact: true },
        { label: "Donor Details",       path: "/super-admin/blood-bank/donor",           icon: <HeartHandshake size={13} /> },
        { label: "Blood Issue Details", path: "/super-admin/blood-bank/blood-issue",     icon: <Droplets size={13} /> },
        { label: "Component Issue",     path: "/super-admin/blood-bank/component-issue", icon: <Package size={13} /> },
      ],
    }),
    createItem({
      label: "IVF",
      path: ROUTES.SUPER_ADMIN.IVF,
      icon: <HeartPulse size={17} />,
      group: "Clinical",
      permissionKey: { resource: "ivf", action: "view" },
      subItems: [
        { label: "Overview",           path: "/super-admin/ivf",                     icon: <LayoutDashboard size={13} />, exact: true },
        { label: "Patients",           path: "/super-admin/ivf/patients",            icon: <Baby size={13} /> },
        { label: "Procedure Calendar", path: "/super-admin/ivf/procedure-calender",  icon: <CalendarIcon size={13} /> },
        // { label: "Report",             path: "/super-admin/ivf/reports",             icon: <BarChart2 size={13} /> },
      ],
    }),
    createItem({
      label: "OT",
      path: "/super-admin/ot",
      icon: <Scissors size={17} />,
      group: "Clinical",
      permissionKey: { resource: "ot", action: "view" },
      subItems: [
        { label: "Overview",  path: "/super-admin/ot",           icon: <LayoutDashboard size={13} />, exact: true },
        { label: "Pre-OT",    path: "/super-admin/ot/pre-ot",    icon: <ClipboardCheckIcon size={13} /> },
        { label: "Inventory", path: "/super-admin/ot/inventory", icon: <PackageOpen size={13} /> },
        { label: "Pharma",    path: "/super-admin/ot/ot-pharma", icon: <PillIcon size={13} /> },
        { label: "OT Bill",   path: "/super-admin/ot/bill",      icon: <ReceiptIcon size={13} /> },
      ],
    }),

    /* ── SERVICES ── */
    createItem({
      label: "Pharmacy",
      path: ROUTES.SUPER_ADMIN.PHARMA,
      icon: <Pill size={17} />,
      group: "Services",

      permissionKey: [
    { resource: "pharmacy",           action: "view"   },
    { resource: "sell_medicine",      action: "create" },
    { resource: "sell_medicine",      action: "read"   },
    { resource: "purchase_medicine",  action: "read"   },
    { resource: "purchase_return",    action: "read"   },
    { resource: "sales_return",       action: "read"   },
    { resource: "medicine",           action: "read"   },
    { resource: "medicine_category",  action: "read"   },
    { resource: "medicine_subcategory", action: "read" },
    { resource: "supplier",           action: "read"   },
    { resource: "expiry",             action: "read"   },
    { resource: "stock_ledger",       action: "read"   },
    { resource: "pharmacy_report",    action: "read"   },
  ],
  subItems: [
    { label: "Overview",             path: "/super-admin/pharma",                        icon: <LayoutDashboard size={13} />, exact: true },
    { label: "Sell",                 path: "/super-admin/pharma/sell",                   icon: <ShoppingCart size={13} />,    permissionKey: { resource: "sell_medicine",       action: "create" } },
    { label: "Purchase",             path: "/super-admin/pharma/medicines/purchasepage", icon: <Truck size={13} />,           permissionKey: { resource: "purchase_medicine",   action: "read"   } },
    { label: "Purchase Returns",     path: "/super-admin/pharma/purchase-returns",       icon: <ArrowLeftRight size={13} />,  permissionKey: { resource: "purchase_return",     action: "read"   } },
    { label: "Sales Returns",        path: "/super-admin/pharma/sales-returns",          icon: <ArrowLeftRight size={13} />,  permissionKey: { resource: "sales_return",        action: "read"   } },
    { label: "Medicine Master",      path: "/super-admin/pharma/item-master",            icon: <Package size={13} />,         permissionKey: { resource: "medicine",            action: "read"   } },
    { label: "Medicine Category",    path: "/super-admin/pharma/item-category",          icon: <Tags size={13} />,            permissionKey: { resource: "medicine_category",   action: "read"   } },
    { label: "Medicine SubCategory", path: "/super-admin/pharma/itemsubcategory",        icon: <Tags size={13} />,            permissionKey: { resource: "medicine_subcategory", action: "read"  } },
    { label: "Self Master",          path: "/super-admin/pharma/self-master",            icon: <UserRound size={13} />,       permissionKey: { resource: "medicine_self",        action: "read"  } },
    { label: "Supplier",             path: "/super-admin/pharma/supplier",               icon: <Building size={13} />,        permissionKey: { resource: "supplier",            action: "read"   } },
    { label: "Expiry",               path: "/super-admin/pharma/expiry",                 icon: <AlertTriangleIcon size={13} />, permissionKey: { resource: "expiry",            action: "read"   } },
    { label: "Stock Ledger",         path: "/super-admin/pharma/stock-ledger",           icon: <ClipboardList size={13} />,   permissionKey: { resource: "stock_ledger",        action: "read"   } },
    { label: "Reports",              path: "/super-admin/pharma/reports",                icon: <BarChart3 size={13} />,       permissionKey: { resource: "pharmacy_report",     action: "read"   } },
  ],

    }),

    /* ── MANAGEMENT ── */
    createItem({
      label: "Hospitals",
      path: ROUTES.SUPER_ADMIN.HOSPITALS,
      icon: <Building2 size={17} />,
      group: "Management",
      permissionKey: { resource: "hospital", action: "view" },
      subItems: [
        { label: "Overview",   path: "/super-admin/hospitals",                  icon: <LayoutDashboard size={13} />, exact: true },
        { label: "Hospital",   path: "/super-admin/hospitals/hospital",         icon: <HospitalIcon size={13} /> },
        { label: "Department", path: "/super-admin/hospitals/department",       icon: <ListOrdered size={13} /> },
        { label: "Doctors",    path: "/super-admin/hospitals/hospital-doctors", icon: <UserRound size={13} /> },
      ],
    }),
    createItem({
      label: "Stocks",
      path: ROUTES.SUPER_ADMIN.STOCKS,
      icon: <Package size={17} />,
      group: "Management",
      permissionKey: { resource: "stock", action: "read" },
              subItems: [
    {
      label: "Stock Item",
      path: "/super-admin/stocks/item",
      icon: <PackageOpen size={13} />,
    },
    {
      label: "Stock Master",
      path: "/super-admin/stocks/master",
      icon: <Package size={13} />,
    },
    {
      label: "In Stock",
      path: "/super-admin/stocks/instock",
      icon: <PackageCheck size={13} />,
    },
    {
      label: "Out Stock",
      path: "/super-admin/stocks/outstock",
      icon: <PackageMinus size={13} />,
    },
  ],
    }),
    createItem({
      label: "User",
      path: ROUTES.SUPER_ADMIN.USER_MANAGEMENT,
      icon: <Users size={17} />,
      group: "Management",
      permissionKey: { resource: "user", action: "read" },
    }),
    createItem({
      label: "Roles",
      path: ROUTES.SUPER_ADMIN.ROLES,
      icon: <ShieldCheck size={17} />,
      group: "Management",
      permissionKey: { resource: "role", action: "read" },
    }),
    createItem({
      label: "Permissions",
      path: ROUTES.SUPER_ADMIN.PERMISSIONS,
      icon: <KeyRound size={17} />,
      group: "Management",
      permissionKey: { resource: "permission", action: "read" },
    }),

    /* ── BILLING ── */
    createItem({
      label: "Appointment Bill",
      path: ROUTES.SUPER_ADMIN.APPOINTMENT_BILL,
      icon: <Receipt size={17} />,
      group: "Billing",
      permissionKey: { resource: "appointment_billing", action: "read" },
    }),
    createItem({
      label: "Pathology Bill",
      path: ROUTES.SUPER_ADMIN.PATHOLOGY_BILL,
      icon: <FlaskConical size={17} />,
      group: "Billing",
      permissionKey: { resource: "pathology_invoice", action: "read" },
    }),
    createItem({
      label: "Radiology Bill",
      path: ROUTES.SUPER_ADMIN.RADIOLOGY_BILL,
      icon: <Scan size={17} />,
      group: "Billing",
      permissionKey: { resource: "radiology_invoice", action: "read" },
    }),

    createItem({ label: "Pharmacy Bill", path: ROUTES.SUPER_ADMIN.PHARMACY_BILL, icon: <Pill size={17} />, group: "Billing", permissionKey: { resource: "sell_medicine", action: "read" } }),

    /* ── ACCOUNT ── */
    createItem({
      label: "My Profile",
      path: ROUTES.PROFILE,
      icon: <UserCircle size={17} />,
      group: "Account",
    }),
    createItem({
      label: "Settings",
      path: ROUTES.SETTINGS,
      icon: <Settings size={17} />,
      group: "Account",
    }),
  ],

  // ─────────────────────────────────────────────────────────────
  // ALL OTHER ROLES — completely unchanged from original
  // ─────────────────────────────────────────────────────────────

  [ROLES.SUB_ADMIN]: [
    createItem({ role: ROLES.SUB_ADMIN, label: "Dashboard", path: ROUTES.SUB_ADMIN.DASHBOARD, icon: <LayoutDashboard size={17} />, group: "Main", permissionKey: { resource: "dashboard", action: "view" } }),
    createItem({ role: ROLES.SUB_ADMIN, label: "Hospital Management", path: ROUTES.SUB_ADMIN.HOSPITALS, icon: <Building2 size={17} />, group: "Management", permissionKey: { resource: "hospital", action: "view" } }),
    createItem({ role: ROLES.SUB_ADMIN, label: "User Management", path: ROUTES.SUB_ADMIN.USERS, icon: <Users size={17} />, group: "Management", permissionKey: { resource: "user", action: "view" } }),
    createItem({ role: ROLES.SUB_ADMIN, label: "Reports", path: ROUTES.SUB_ADMIN.REPORTS, icon: <FileText size={17} />, group: "Reports", permissionKey: { resource: "report", action: "view" } }),
    createItem({ role: ROLES.SUB_ADMIN, label: "IPD", path: ROUTES.SUB_ADMIN.IPD, icon: <BedDouble size={17} />, group: "Hospital Modules", permissionKey: { resource: "ipd", action: "view" } }),
    createItem({ role: ROLES.SUB_ADMIN, label: "OPD", path: ROUTES.SUB_ADMIN.OPD, icon: <Stethoscope size={17} />, group: "Hospital Modules", permissionKey: { resource: "opd", action: "view" } }),
    createItem({ role: ROLES.SUB_ADMIN, label: "Pharmacy", path: ROUTES.SUB_ADMIN.PHARMA, icon: <Pill size={17} />, group: "Hospital Modules", permissionKey: { resource: "pharmacy", action: "view" } }),
    createItem({ role: ROLES.SUB_ADMIN, label: "Ambulance", path: ROUTES.SUB_ADMIN.AMBULANCE_MGT, icon: <Ambulance size={17} />, group: "Hospital Modules", permissionKey: { resource: "ambulance", action: "view" } }),
    createItem({ role: ROLES.SUB_ADMIN, label: "Appointments", path: ROUTES.SUB_ADMIN.APPOINTMENTS, icon: <CalendarCheck size={17} />, group: "Hospital Modules", permissionKey: { resource: "appointment", action: "view" } }),
    createItem({ role: ROLES.SUB_ADMIN, label: "Doctors", path: ROUTES.SUB_ADMIN.DOCTORS, icon: <UserRound size={17} />, group: "Hospital Modules", permissionKey: { resource: "doctor", action: "view" } }),
    createItem({ role: ROLES.SUB_ADMIN, label: "Patients", path: ROUTES.SUB_ADMIN.PATIENTS, icon: <ClipboardList size={17} />, group: "Hospital Modules", permissionKey: { resource: "patient", action: "view" } }),
    createItem({ role: ROLES.SUB_ADMIN, label: "IVF", path: ROUTES.SUB_ADMIN.IVF, icon: <HeartPulse size={17} />, group: "Hospital Modules", permissionKey: { resource: "ivf", action: "view" } }),
    createItem({ role: ROLES.SUB_ADMIN, label: "Pathology", path: ROUTES.SUB_ADMIN.PATHOLOGY, icon: <FlaskConical size={17} />, group: "Hospital Modules", permissionKey: { resource: "pathology", action: "view" } }),
    createItem({ role: ROLES.SUB_ADMIN, label: "Radiology", path: ROUTES.SUB_ADMIN.RADIOLOGY, icon: <Scan size={17} />, group: "Hospital Modules", permissionKey: { resource: "radiology", action: "view" } }),
    createItem({ role: ROLES.SUB_ADMIN, label: "Blood Bank", path: ROUTES.SUB_ADMIN.BLOOD_BANK_STATUS, icon: <Droplets size={17} />, group: "Hospital Modules", permissionKey: { resource: "bloodBank", action: "view" } }),
    createItem({ role: ROLES.SUB_ADMIN, label: "My Profile", path: ROUTES.PROFILE, icon: <UserCircle size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "profile", action: "view" } }),
    createItem({ role: ROLES.SUB_ADMIN, label: "Settings", path: ROUTES.SETTINGS, icon: <Settings size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "settings", action: "view" } }),
  ],

  [ROLES.HOSPITAL_ADMIN]: [
    createItem({ role: ROLES.HOSPITAL_ADMIN, label: "Dashboard", path: ROUTES.HOSPITAL_ADMIN.DASHBOARD, icon: <LayoutDashboard size={17} />, group: "Main", permissionKey: { resource: "dashboard", action: "view" } }),
    createItem({ role: ROLES.HOSPITAL_ADMIN, label: "Doctors", path: ROUTES.HOSPITAL_ADMIN.DOCTORS, icon: <Stethoscope size={17} />, group: "Hospital", permissionKey: { resource: "doctor", action: "view" } }),
    createItem({ role: ROLES.HOSPITAL_ADMIN, label: "Staff", path: ROUTES.HOSPITAL_ADMIN.STAFF, icon: <Users size={17} />, group: "Hospital", permissionKey: { resource: "staff", action: "view" } }),
    createItem({ role: ROLES.HOSPITAL_ADMIN, label: "Departments", path: ROUTES.HOSPITAL_ADMIN.DEPARTMENTS, icon: <Building size={17} />, group: "Hospital", permissionKey: { resource: "department", action: "view" } }),
    createItem({ role: ROLES.HOSPITAL_ADMIN, label: "Wards & Beds", path: ROUTES.HOSPITAL_ADMIN.WARDS, icon: <BedDouble size={17} />, group: "Hospital", permissionKey: { resource: "ward", action: "view" } }),
    createItem({ role: ROLES.HOSPITAL_ADMIN, label: "Inventory", path: ROUTES.HOSPITAL_ADMIN.INVENTORY, icon: <Package size={17} />, group: "Operations", permissionKey: { resource: "inventory", action: "view" } }),
    createItem({ role: ROLES.HOSPITAL_ADMIN, label: "Reports", path: ROUTES.HOSPITAL_ADMIN.REPORTS, icon: <FileText size={17} />, group: "Operations", permissionKey: { resource: "report", action: "view" } }),
    createItem({ role: ROLES.HOSPITAL_ADMIN, label: "Settings", path: ROUTES.HOSPITAL_ADMIN.SETTINGS, icon: <Settings size={17} />, group: "System", permissionKey: { resource: "settings", action: "view" } }),
    createItem({ role: ROLES.HOSPITAL_ADMIN, label: "My Profile", path: ROUTES.PROFILE, icon: <UserCircle size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "profile", action: "view" } }),
    createItem({ role: ROLES.HOSPITAL_ADMIN, label: "Preferences", path: ROUTES.SETTINGS, icon: <Settings size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "settings", action: "view" } }),
  ],

  [ROLES.FRONT_DESK]: [
    createItem({ role: ROLES.FRONT_DESK, label: "Dashboard", path: ROUTES.FRONT_DESK.DASHBOARD, icon: <LayoutDashboard size={17} />, group: "Main", permissionKey: { resource: "dashboard", action: "view" } }),
    createItem({ role: ROLES.FRONT_DESK, label: "Patients", path: ROUTES.FRONT_DESK.PATIENTS, icon: <Users size={17} />, group: "Patients", permissionKey: { resource: "patient", action: "view" } }),
    createItem({ role: ROLES.FRONT_DESK, label: "Patient Registration", path: ROUTES.FRONT_DESK.REGISTRATION, icon: <UserPlus size={17} />, group: "Patients", permissionKey: { resource: "patient", action: "create" } }),
    createItem({ role: ROLES.FRONT_DESK, label: "Appointments", path: ROUTES.FRONT_DESK.APPOINTMENTS, icon: <Calendar size={17} />, group: "Patients", permissionKey: { resource: "appointment", action: "view" } }),
    createItem({ role: ROLES.FRONT_DESK, label: "Token Queue", path: ROUTES.FRONT_DESK.TOKEN_QUEUE, icon: <Ticket size={17} />, group: "Patients", permissionKey: { resource: "token", action: "view" } }),
    createItem({ role: ROLES.FRONT_DESK, label: "OPD", path: ROUTES.FRONT_DESK.OPD, icon: <Clipboard size={17} />, group: "Wards", permissionKey: { resource: "opd", action: "view" } }),
    createItem({ role: ROLES.FRONT_DESK, label: "IPD", path: ROUTES.FRONT_DESK.IPD, icon: <BedDouble size={17} />, group: "Wards", permissionKey: { resource: "ipd", action: "view" } }),
    createItem({ role: ROLES.FRONT_DESK, label: "Pharmacy", path: ROUTES.FRONT_DESK.PHARMACY, icon: <Pill size={17} />, group: "Pharmacy", permissionKey: { resource: "pharmacy", action: "view" } }),
    createItem({ role: ROLES.FRONT_DESK, label: "Radiology", path: ROUTES.FRONT_DESK.RADIOLOGY, icon: <Camera size={17} />, group: "Laboratory", permissionKey: { resource: "radiology", action: "view" } }),
    createItem({ role: ROLES.FRONT_DESK, label: "Pathology", path: ROUTES.FRONT_DESK.PATHOLOGY, icon: <FlaskConical size={17} />, group: "Laboratory", permissionKey: { resource: "pathology", action: "view" } }),
    createItem({ role: ROLES.FRONT_DESK, label: "Ambulance", path: ROUTES.FRONT_DESK.AMBULANCE, icon: <Ambulance size={17} />, group: "Services", permissionKey: { resource: "ambulance", action: "view" } }),
    createItem({ role: ROLES.FRONT_DESK, label: "Billing", path: ROUTES.FRONT_DESK.BILLING, icon: <Receipt size={17} />, group: "Finance", permissionKey: { resource: "billing", action: "view" } }),
    createItem({ role: ROLES.FRONT_DESK, label: "My Profile", path: ROUTES.PROFILE, icon: <UserCircle size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "profile", action: "view" } }),
    createItem({ role: ROLES.FRONT_DESK, label: "Settings", path: ROUTES.SETTINGS, icon: <Settings size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "settings", action: "view" } }),
  ],

  [ROLES.ACCOUNTANT]: [
    createItem({ role: ROLES.ACCOUNTANT, label: "Dashboard", path: ROUTES.ACCOUNTANT.DASHBOARD, icon: <LayoutDashboard size={17} />, group: "Main", permissionKey: { resource: "dashboard", action: "view" } }),
    createItem({ role: ROLES.ACCOUNTANT, label: "Patients", path: ROUTES.ACCOUNTANT.PATIENTS, icon: <Users size={17} />, group: "Patients", permissionKey: { resource: "patient", action: "view" } }),
    createItem({ role: ROLES.ACCOUNTANT, label: "Billing", path: ROUTES.ACCOUNTANT.BILLING, icon: <Receipt size={17} />, group: "Finance", permissionKey: { resource: "bill", action: "view" } }),
    createItem({ role: ROLES.ACCOUNTANT, label: "Appointments", path: ROUTES.ACCOUNTANT.APPOINTMENTS, icon: <Calendar size={17} />, group: "Patients", permissionKey: { resource: "appointment", action: "view" } }),
    createItem({ role: ROLES.ACCOUNTANT, label: "OPD", path: ROUTES.ACCOUNTANT.OPD, icon: <Clipboard size={17} />, group: "Wards", permissionKey: { resource: "opd", action: "view" } }),
    createItem({ role: ROLES.ACCOUNTANT, label: "IPD", path: ROUTES.ACCOUNTANT.IPD, icon: <BedDouble size={17} />, group: "Wards", permissionKey: { resource: "ipd", action: "view" } }),
    createItem({ role: ROLES.ACCOUNTANT, label: "Pharmacy", path: ROUTES.ACCOUNTANT.PHARMACY, icon: <Pill size={17} />, group: "Pharmacy", permissionKey: { resource: "pharmacy", action: "view" } }),
    createItem({ role: ROLES.ACCOUNTANT, label: "Pathology", path: ROUTES.ACCOUNTANT.PATHOLOGY, icon: <FlaskConical size={17} />, group: "Laboratory", permissionKey: { resource: "pathology", action: "view" } }),
    createItem({ role: ROLES.ACCOUNTANT, label: "Radiology", path: ROUTES.ACCOUNTANT.RADIOLOGY, icon: <Camera size={17} />, group: "Laboratory", permissionKey: { resource: "radiology", action: "view" } }),
    createItem({ role: ROLES.ACCOUNTANT, label: "Ambulance", path: ROUTES.ACCOUNTANT.AMBULANCE, icon: <Ambulance size={17} />, group: "Services", permissionKey: { resource: "ambulance", action: "view" } }),
    createItem({ role: ROLES.ACCOUNTANT, label: "Payments", path: ROUTES.ACCOUNTANT.PAYMENTS, icon: <CreditCard size={17} />, group: "Finance", permissionKey: { resource: "payment", action: "view" } }),
    createItem({ role: ROLES.ACCOUNTANT, label: "Expenses", path: ROUTES.ACCOUNTANT.EXPENSES, icon: <TrendingDown size={17} />, group: "Finance", permissionKey: { resource: "expense", action: "view" } }),
    createItem({ role: ROLES.ACCOUNTANT, label: "Insurance", path: ROUTES.ACCOUNTANT.INSURANCE, icon: <Shield size={17} />, group: "Finance", permissionKey: { resource: "insurance", action: "view" } }),
    createItem({ role: ROLES.ACCOUNTANT, label: "Reports", path: ROUTES.ACCOUNTANT.REPORTS, icon: <FileText size={17} />, group: "Reports", permissionKey: { resource: "report", action: "view" } }),
    createItem({ role: ROLES.ACCOUNTANT, label: "My Profile", path: ROUTES.PROFILE, icon: <UserCircle size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "profile", action: "view" } }),
    createItem({ role: ROLES.ACCOUNTANT, label: "Settings", path: ROUTES.SETTINGS, icon: <Settings size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "settings", action: "view" } }),
  ],

  [ROLES.NURSE]: [
    createItem({ role: ROLES.NURSE, label: "Dashboard", path: ROUTES.NURSE.DASHBOARD, icon: <LayoutDashboard size={17} />, group: "Main", permissionKey: { resource: "dashboard", action: "view" } }),
    createItem({ role: ROLES.NURSE, label: "Patients", path: ROUTES.NURSE.PATIENTS, icon: <Users size={17} />, group: "Patient Care", permissionKey: { resource: "patient", action: "view" } }),
    createItem({ role: ROLES.NURSE, label: "IPD", path: ROUTES.NURSE.IPD, icon: <Clipboard size={17} />, group: "Patient Care", permissionKey: { resource: "ipd", action: "view" } }),
    createItem({ role: ROLES.NURSE, label: "OPD", path: ROUTES.NURSE.OPD, icon: <BedDouble size={17} />, group: "Patient Care", permissionKey: { resource: "opd", action: "view" } }),
    createItem({ role: ROLES.NURSE, label: "Patient Vitals", path: ROUTES.NURSE.VITALS, icon: <HeartPulse size={17} />, group: "Patient Care", permissionKey: { resource: "vital", action: "view" } }),
    createItem({ role: ROLES.NURSE, label: "Medication", path: ROUTES.NURSE.MEDICATION, icon: <Pill size={17} />, group: "Patient Care", permissionKey: { resource: "medication", action: "view" } }),
    createItem({ role: ROLES.NURSE, label: "Ward Mgmt", path: ROUTES.NURSE.WARD, icon: <BedDouble size={17} />, group: "Ward", permissionKey: { resource: "ward", action: "view" } }),
    createItem({ role: ROLES.NURSE, label: "Care Plans", path: ROUTES.NURSE.CARE_PLANS, icon: <ClipboardList size={17} />, group: "Ward", permissionKey: { resource: "carePlan", action: "view" } }),
    createItem({ role: ROLES.NURSE, label: "Shift Handover", path: ROUTES.NURSE.HANDOVER, icon: <ArrowLeftRight size={17} />, group: "Ward", permissionKey: { resource: "handover", action: "view" } }),
    createItem({ role: ROLES.NURSE, label: "My Profile", path: ROUTES.PROFILE, icon: <UserCircle size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "profile", action: "view" } }),
    createItem({ role: ROLES.NURSE, label: "Settings", path: ROUTES.SETTINGS, icon: <Settings size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "settings", action: "view" } }),
  ],

  [ROLES.LABORATORY]: [
    createItem({ role: ROLES.LABORATORY, label: "Dashboard", path: ROUTES.LABORATORY.DASHBOARD, icon: <LayoutDashboard size={17} />, group: "Main", permissionKey: { resource: "dashboard", action: "view" } }),
    createItem({ role: ROLES.LABORATORY, label: "Test Orders", path: ROUTES.LABORATORY.TEST_ORDERS, icon: <FlaskConical size={17} />, group: "Lab Work", permissionKey: { resource: "labOrder", action: "view" } }),
    createItem({ role: ROLES.LABORATORY, label: "Test Results", path: ROUTES.LABORATORY.TEST_RESULTS, icon: <FileCheck size={17} />, group: "Lab Work", permissionKey: { resource: "labResult", action: "view" } }),
    createItem({ role: ROLES.LABORATORY, label: "Sample Collection", path: ROUTES.LABORATORY.SAMPLES, icon: <Droplets size={17} />, group: "Lab Work", permissionKey: { resource: "sample", action: "view" } }),
    createItem({ role: ROLES.LABORATORY, label: "Test Catalog", path: ROUTES.LABORATORY.CATALOG, icon: <BookOpen size={17} />, group: "Reference", permissionKey: { resource: "catalog", action: "view" } }),
    createItem({ role: ROLES.LABORATORY, label: "Reports", path: ROUTES.LABORATORY.REPORTS, icon: <FileText size={17} />, group: "Reference", permissionKey: { resource: "report", action: "view" } }),
    createItem({ role: ROLES.LABORATORY, label: "My Profile", path: ROUTES.PROFILE, icon: <UserCircle size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "profile", action: "view" } }),
    createItem({ role: ROLES.LABORATORY, label: "Settings", path: ROUTES.SETTINGS, icon: <Settings size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "settings", action: "view" } }),
  ],

  [ROLES.RADIOLOGY]: [
    createItem({ role: ROLES.RADIOLOGY, label: "Dashboard", path: ROUTES.RADIOLOGY.DASHBOARD, icon: <LayoutDashboard size={17} />, group: "Main", permissionKey: { resource: "dashboard", action: "view" } }),
    createItem({ role: ROLES.RADIOLOGY, label: "Patients", path: ROUTES.RADIOLOGY.PATIENTS, icon: <Users size={17} />, group: "Radiology", permissionKey: { resource: "patient", action: "view" } }),
    createItem({ role: ROLES.RADIOLOGY, label: "Billing", path: ROUTES.RADIOLOGY.BILLING, icon: <CreditCard size={17} />, group: "Radiology", permissionKey: { resource: "billing", action: "view" } }),
    createItem({ role: ROLES.RADIOLOGY, label: "OPD", path: ROUTES.RADIOLOGY.OPD, icon: <Stethoscope size={17} />, group: "Radiology", permissionKey: { resource: "opd", action: "view" } }),
    createItem({ role: ROLES.RADIOLOGY, label: "IPD", path: ROUTES.RADIOLOGY.IPD, icon: <BedDouble size={17} />, group: "Radiology", permissionKey: { resource: "ipd", action: "view" } }),
    createItem({ role: ROLES.RADIOLOGY, label: "Reports", path: ROUTES.RADIOLOGY.REPORTS, icon: <FileText size={17} />, group: "Radiology", permissionKey: { resource: "report", action: "view" } }),
    createItem({ role: ROLES.RADIOLOGY, label: "Scan Orders", path: ROUTES.RADIOLOGY.SCAN_ORDERS, icon: <ScanLine size={17} />, group: "Radiology", permissionKey: { resource: "scanOrder", action: "view" } }),
    createItem({ role: ROLES.RADIOLOGY, label: "Scan Results", path: ROUTES.RADIOLOGY.SCAN_RESULTS, icon: <ImageIcon size={17} />, group: "Radiology", permissionKey: { resource: "scanResult", action: "view" } }),
    createItem({ role: ROLES.RADIOLOGY, label: "Imaging", path: ROUTES.RADIOLOGY.IMAGING, icon: <Monitor size={17} />, group: "Radiology", permissionKey: { resource: "imaging", action: "view" } }),
    createItem({ role: ROLES.RADIOLOGY, label: "Equipment", path: ROUTES.RADIOLOGY.EQUIPMENT, icon: <Wrench size={17} />, group: "Resources", permissionKey: { resource: "equipment", action: "view" } }),
    createItem({ role: ROLES.RADIOLOGY, label: "Test Catalog", path: ROUTES.RADIOLOGY.CATALOG, icon: <FileText size={17} />, group: "Resources", permissionKey: { resource: "catalog", action: "view" } }),
    createItem({ role: ROLES.RADIOLOGY, label: "My Profile", path: ROUTES.PROFILE, icon: <UserCircle size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "profile", action: "view" } }),
    createItem({ role: ROLES.RADIOLOGY, label: "Settings", path: ROUTES.SETTINGS, icon: <Settings size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "settings", action: "view" } }),
  ],

  [ROLES.AMBULANCE]: [
    createItem({ role: ROLES.AMBULANCE, label: "Dashboard", path: ROUTES.AMBULANCE.DASHBOARD, icon: <LayoutDashboard size={17} />, group: "Main", permissionKey: { resource: "dashboard", action: "view" } }),
    createItem({ role: ROLES.AMBULANCE, label: "Dispatch", path: ROUTES.AMBULANCE.DISPATCH, icon: <Radio size={17} />, group: "Operations", permissionKey: { resource: "dispatch", action: "view" } }),
    createItem({ role: ROLES.AMBULANCE, label: "Fleet", path: ROUTES.AMBULANCE.FLEET, icon: <Truck size={17} />, group: "Operations", permissionKey: { resource: "fleet", action: "view" } }),
    createItem({ role: ROLES.AMBULANCE, label: "Calls", path: ROUTES.AMBULANCE.CALLS, icon: <Phone size={17} />, group: "Operations", permissionKey: { resource: "call", action: "view" } }),
    createItem({ role: ROLES.AMBULANCE, label: "Drivers", path: ROUTES.AMBULANCE.DRIVERS, icon: <User2 size={17} />, group: "Resources", permissionKey: { resource: "driver", action: "view" } }),
    createItem({ role: ROLES.AMBULANCE, label: "My Profile", path: ROUTES.PROFILE, icon: <UserCircle size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "profile", action: "view" } }),
    createItem({ role: ROLES.AMBULANCE, label: "Settings", path: ROUTES.SETTINGS, icon: <Settings size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "settings", action: "view" } }),
  ],

  [ROLES.PHARMACIST]: [
    createItem({ role: ROLES.PHARMACIST, label: "Dashboard", path: ROUTES.PHARMACIST.DASHBOARD, icon: <LayoutDashboard size={17} />, group: "Main", permissionKey: { resource: "dashboard", action: "view" } }),
    createItem({ role: ROLES.PHARMACIST, label: "Prescriptions", path: ROUTES.PHARMACIST.PRESCRIPTIONS, icon: <FileTextIcon size={17} />, group: "Pharmacy", permissionKey: { resource: "prescription", action: "view" } }),
    createItem({ role: ROLES.PHARMACIST, label: "OPD", path: ROUTES.PHARMACIST.OPD, icon: <FileTextIcon size={17} />, group: "Pharmacy", permissionKey: { resource: "opd", action: "view" } }),
    createItem({ role: ROLES.PHARMACIST, label: "IPD", path: ROUTES.PHARMACIST.IPD, icon: <FileTextIcon size={17} />, group: "Pharmacy", permissionKey: { resource: "ipd", action: "view" } }),
    createItem({ role: ROLES.PHARMACIST, label: "Billing", path: ROUTES.PHARMACIST.BILLING, icon: <FileTextIcon size={17} />, group: "Pharmacy", permissionKey: { resource: "bill", action: "view" } }),
    createItem({ role: ROLES.PHARMACIST, label: "Medicines", path: ROUTES.PHARMACIST.MEDICINES, icon: <Pill size={17} />, group: "Inventory", permissionKey: { resource: "medicine", action: "view" } }),
    createItem({ role: ROLES.PHARMACIST, label: "Stock", path: ROUTES.PHARMACIST.STOCK, icon: <Boxes size={17} />, group: "Inventory", permissionKey: { resource: "stock", action: "view" } }),
    createItem({ role: ROLES.PHARMACIST, label: "Purchase Orders", path: ROUTES.PHARMACIST.PURCHASE_ORDERS, icon: <ShoppingCart size={17} />, group: "Supply", permissionKey: { resource: "purchaseOrder", action: "view" } }),
    createItem({ role: ROLES.PHARMACIST, label: "Suppliers", path: ROUTES.PHARMACIST.SUPPLIERS, icon: <Truck size={17} />, group: "Supply", permissionKey: { resource: "supplier", action: "view" } }),
    createItem({ role: ROLES.PHARMACIST, label: "Sales", path: ROUTES.PHARMACIST.SALES, icon: <Receipt size={17} />, group: "Transactions", permissionKey: { resource: "sale", action: "view" } }),
    createItem({ role: ROLES.PHARMACIST, label: "Purchases", path: ROUTES.PHARMACIST.PURCHASES, icon: <ShoppingCart size={17} />, group: "Transactions", permissionKey: { resource: "purchase", action: "view" } }),
    createItem({ role: ROLES.PHARMACIST, label: "Purchase Returns", path: ROUTES.PHARMACIST.PURCHASE_RETURNS, icon: <ArrowLeftRight size={17} />, group: "Returns", permissionKey: { resource: "return", action: "view" } }),
    createItem({ role: ROLES.PHARMACIST, label: "Sales Returns", path: ROUTES.PHARMACIST.SALES_RETURNS, icon: <ArrowLeftRight size={17} />, group: "Returns", permissionKey: { resource: "return", action: "view" } }),
    createItem({ role: ROLES.PHARMACIST, label: "Expiry", path: ROUTES.PHARMACIST.EXPIRY, icon: <AlertTriangleIcon size={17} />, group: "Inventory", permissionKey: { resource: "expiry", action: "view" } }),
    createItem({ role: ROLES.PHARMACIST, label: "Stock Ledger", path: ROUTES.PHARMACIST.STOCK_LEDGER, icon: <ClipboardList size={17} />, group: "Inventory", permissionKey: { resource: "stockLedger", action: "view" } }),
    createItem({ role: ROLES.PHARMACIST, label: "Reports", path: ROUTES.PHARMACIST.REPORTS, icon: <FileText size={17} />, group: "Analytics", permissionKey: { resource: "report", action: "view" } }),
    createItem({ role: ROLES.PHARMACIST, label: "My Profile", path: ROUTES.PROFILE, icon: <UserCircle size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "profile", action: "view" } }),
    createItem({ role: ROLES.PHARMACIST, label: "Settings", path: ROUTES.SETTINGS, icon: <Settings size={17} />, group: "Account", allowedRoles: ALL_ROLES, permissionKey: { resource: "settings", action: "view" } }),
  ],

  // ── Doctor ──────────────────────────────────────────────────────────────
  [ROLES.DOCTOR]: [
    createItem({ role: ROLES.DOCTOR, label: "Dashboard",  path: ROUTES.DOCTOR.DASHBOARD,  icon: <LayoutDashboard size={17} />, group: "Main" }),
    createItem({ role: ROLES.DOCTOR, label: "Patients",   path: ROUTES.DOCTOR.PATIENTS,   icon: <Users size={17} />,          group: "Patient Flow", permissionKey: { resource: "patient",        action: "read" } }),
    createItem({ role: ROLES.DOCTOR, label: "OPD",        path: ROUTES.DOCTOR.OPD,        icon: <Stethoscope size={17} />,    group: "Clinical",     permissionKey: { resource: "opd",            action: "read" } }),
    // createItem({ role: ROLES.DOCTOR, label: "IPD",        path: ROUTES.DOCTOR.IPD,        icon: <BedDouble size={17} />,      group: "Clinical",     permissionKey: { resource: "ipd_admission",  action: "read" } }),
    createItem({ role: ROLES.DOCTOR, label: "IPD", path: ROUTES.DOCTOR.IPD, icon: <BedDouble size={17} />, group: "Clinical", permissionKey: [
  { resource: "ipd_admission", action: "read" },
  { resource: "ipd_discharge", action: "read" },
  { resource: "ward",          action: "read" },
  { resource: "room",          action: "read" },
  { resource: "bed",           action: "read" },
  { resource: "ipd",           action: "view" },
]}),
    createItem({ role: ROLES.DOCTOR, label: "Emergency",  path: ROUTES.DOCTOR.EMERGENCY,  icon: <HeartPulse size={17} />,     group: "Clinical",     permissionKey: { resource: "emergency",      action: "read" } }),
    createItem({ role: ROLES.DOCTOR, label: "IVF",        path: ROUTES.DOCTOR.IVF,        icon: <FlaskConical size={17} />,   group: "Clinical",     permissionKey: { resource: "ivf",            action: "read" } }),
    createItem({ role: ROLES.DOCTOR, label: "OT",         path: ROUTES.DOCTOR.OT,         icon: <Scissors size={17} />,       group: "Clinical",     permissionKey: { resource: "ot",             action: "read" } }),
    createItem({ role: ROLES.DOCTOR, label: "My Profile", path: ROUTES.PROFILE,           icon: <UserCircle size={17} />,     group: "Account" }),
    createItem({ role: ROLES.DOCTOR, label: "Settings",   path: ROUTES.SETTINGS,          icon: <Settings size={17} />,       group: "Account" }),
  ],

  // ── Receptionist ────────────────────────────────────────────────────────
  [ROLES.RECEPTIONIST]: [
    createItem({ role: ROLES.RECEPTIONIST, label: "Dashboard",  path: ROUTES.RECEPTIONIST.DASHBOARD, icon: <LayoutDashboard size={17} />, group: "Main" }),
    createItem({ role: ROLES.RECEPTIONIST, label: "Patients",   path: ROUTES.RECEPTIONIST.PATIENTS,  icon: <Users size={17} />,          group: "Patient Flow" }),
    createItem({ role: ROLES.RECEPTIONIST, label: "OPD",        path: ROUTES.RECEPTIONIST.OPD,       icon: <Stethoscope size={17} />,    group: "Clinical" }),
    createItem({ role: ROLES.RECEPTIONIST, label: "IPD",        path: ROUTES.RECEPTIONIST.IPD,       icon: <BedDouble size={17} />,      group: "Clinical" }),
    createItem({ role: ROLES.RECEPTIONIST, label: "Emergency",  path: ROUTES.RECEPTIONIST.EMERGENCY, icon: <HeartPulse size={17} />,     group: "Clinical" }),
    createItem({ role: ROLES.RECEPTIONIST, label: "Doctors",    path: ROUTES.RECEPTIONIST.DOCTORS,   icon: <UserRound size={17} />,      group: "Clinical" }),
    // createItem({ role: ROLES.RECEPTIONIST, label: "My Profile", path: ROUTES.PROFILE,                icon: <UserCircle size={17} />,     group: "Account" }),
    // createItem({ role: ROLES.RECEPTIONIST, label: "Settings",   path: ROUTES.SETTINGS,               icon: <Settings size={17} />,       group: "Account" }),
    createItem({ role: ROLES.RECEPTIONIST, label: "My Profile", path: ROUTES.RECEPTIONIST.PROFILE,  icon: <UserCircle size={17} />, group: "Account", permissionKey: { resource: "profile",  action: "view" } }),
    createItem({ role: ROLES.RECEPTIONIST, label: "Settings",   path: ROUTES.RECEPTIONIST.SETTINGS, icon: <Settings size={17} />,  group: "Account", permissionKey: { resource: "settings", action: "view" } }),
  ],

  // ── Lab Technician ──────────────────────────────────────────────────────
  [ROLES.LAB_TECHNICIAN]: [
    createItem({ role: ROLES.LAB_TECHNICIAN, label: "Dashboard",  path: ROUTES.LAB_TECHNICIAN.DASHBOARD,      icon: <LayoutDashboard size={17} />, group: "Main" }),
    createItem({ role: ROLES.LAB_TECHNICIAN, label: "Pathology",  path: ROUTES.LAB_TECHNICIAN.PATHOLOGY,      icon: <FlaskConical size={17} />,    group: "Lab" }),
    createItem({ role: ROLES.LAB_TECHNICIAN, label: "Billing",    path: ROUTES.LAB_TECHNICIAN.PATHOLOGY_BILL, icon: <Receipt size={17} />,         group: "Lab" }),
    createItem({ role: ROLES.LAB_TECHNICIAN, label: "Stocks",     path: ROUTES.LAB_TECHNICIAN.STOCKS,         icon: <Boxes size={17} />,           group: "Inventory" }),
    createItem({ role: ROLES.LAB_TECHNICIAN, label: "My Profile", path: ROUTES.PROFILE,                       icon: <UserCircle size={17} />,      group: "Account" }),
    createItem({ role: ROLES.LAB_TECHNICIAN, label: "Settings",   path: ROUTES.SETTINGS,                      icon: <Settings size={17} />,        group: "Account" }),
  ],

  // ── Radiologist ─────────────────────────────────────────────────────────
  [ROLES.RADIOLOGIST]: [
    createItem({ role: ROLES.RADIOLOGIST, label: "Dashboard",  path: ROUTES.RADIOLOGIST.DASHBOARD,      icon: <LayoutDashboard size={17} />, group: "Main" }),
    createItem({ role: ROLES.RADIOLOGIST, label: "Radiology",  path: ROUTES.RADIOLOGIST.RADIOLOGY,      icon: <ScanLine size={17} />,        group: "Radiology" }),
    createItem({ role: ROLES.RADIOLOGIST, label: "Billing",    path: ROUTES.RADIOLOGIST.RADIOLOGY_BILL, icon: <Receipt size={17} />,         group: "Radiology" }),
    createItem({ role: ROLES.RADIOLOGIST, label: "My Profile", path: ROUTES.PROFILE,                    icon: <UserCircle size={17} />,      group: "Account" }),
    createItem({ role: ROLES.RADIOLOGIST, label: "Settings",   path: ROUTES.SETTINGS,                   icon: <Settings size={17} />,        group: "Account" }),
  ],

  // ── Billing Staff ───────────────────────────────────────────────────────
  [ROLES.BILLING_STAFF]: [
    createItem({ role: ROLES.BILLING_STAFF, label: "Dashboard",        path: ROUTES.BILLING_STAFF.DASHBOARD,        icon: <LayoutDashboard size={17} />, group: "Main" }),
    createItem({ role: ROLES.BILLING_STAFF, label: "Appointment Bill", path: ROUTES.BILLING_STAFF.APPOINTMENT_BILL, icon: <CalendarCheck size={17} />,   group: "Billing" }),
    createItem({ role: ROLES.BILLING_STAFF, label: "Radiology Bill",   path: ROUTES.BILLING_STAFF.RADIOLOGY_BILL,   icon: <ScanLine size={17} />,        group: "Billing" }),
    createItem({ role: ROLES.BILLING_STAFF, label: "Pathology Bill",   path: ROUTES.BILLING_STAFF.PATHOLOGY_BILL,   icon: <FlaskConical size={17} />,    group: "Billing" }),
    createItem({ role: ROLES.BILLING_STAFF, label: "Pharmacy Bill",    path: ROUTES.BILLING_STAFF.PHARMACY_BILL,    icon: <Pill size={17} />,            group: "Billing" }),
    createItem({ role: ROLES.BILLING_STAFF, label: "Stocks",           path: ROUTES.BILLING_STAFF.STOCKS,           icon: <Boxes size={17} />,           group: "Inventory" }),
    createItem({ role: ROLES.BILLING_STAFF, label: "My Profile",       path: ROUTES.PROFILE,                        icon: <UserCircle size={17} />,      group: "Account" }),
    createItem({ role: ROLES.BILLING_STAFF, label: "Settings",         path: ROUTES.SETTINGS,                       icon: <Settings size={17} />,        group: "Account" }),
  ],

  // ── IPD Staff ───────────────────────────────────────────────────────────
  [ROLES.IPD_STAFF]: [
  createItem({ role: ROLES.IPD_STAFF, label: "Dashboard",           path: ROUTES.IPD_STAFF.DASHBOARD,           icon: <LayoutDashboard size={17} />, group: "Main" }),
  createItem({ role: ROLES.IPD_STAFF, label: "IPD",                 path: ROUTES.IPD_STAFF.IPD,                 icon: <BedDouble size={17} />,       group: "IPD",     permissionKey: { resource: "ipd_admission",  action: "read" } }),
  createItem({ role: ROLES.IPD_STAFF, label: "Admitted Patients",   path: ROUTES.IPD_STAFF.ADMITTED_PATIENTS,   icon: <UserPlus size={17} />,        group: "IPD",     permissionKey: { resource: "ipd_admission",  action: "read" } }),
  createItem({ role: ROLES.IPD_STAFF, label: "Discharged Patients", path: ROUTES.IPD_STAFF.DISCHARGED_PATIENTS, icon: <Users size={17} />,           group: "IPD",     permissionKey: { resource: "ipd_discharge",  action: "read" } }),
  createItem({ role: ROLES.IPD_STAFF, label: "Ward",                path: ROUTES.IPD_STAFF.WARD,                icon: <Building2 size={17} />,       group: "IPD",     permissionKey: { resource: "ward",           action: "read" } }),
  createItem({ role: ROLES.IPD_STAFF, label: "Room",                path: ROUTES.IPD_STAFF.ROOM,                icon: <Building size={17} />,        group: "IPD",     permissionKey: { resource: "room",           action: "read" } }),
  createItem({ role: ROLES.IPD_STAFF, label: "Bed",                 path: ROUTES.IPD_STAFF.BED,                 icon: <BedDouble size={17} />,       group: "IPD",     permissionKey: { resource: "bed",            action: "read" } }),
  createItem({ role: ROLES.IPD_STAFF, label: "Bed Status",          path: ROUTES.IPD_STAFF.BED_STATUS,          icon: <Monitor size={17} />,         group: "IPD",     permissionKey: { resource: "bed",            action: "read" } }),
  createItem({ role: ROLES.IPD_STAFF, label: "My Profile",          path: ROUTES.PROFILE,                       icon: <UserCircle size={17} />,      group: "Account" }),
  createItem({ role: ROLES.IPD_STAFF, label: "Settings",            path: ROUTES.SETTINGS,                      icon: <Settings size={17} />,        group: "Account" }),
],
};

export const getSidebarNavItems = (roleKey) => SIDEBAR_NAV_ITEMS[roleKey] || [];
export const MASTER_NAV_ITEMS = SIDEBAR_NAV_ITEMS[ROLES.SUPER_ADMIN];
